<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="$(MSBuildProjectDirectory)/../Solution.Build.props"/>
	
	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="LazyMagic.Client.FactoryGenerator" />
		<PackageReference Include="LazyMagic.Client.ModelGenerator" />
		<PackageReference Include="LazyMagic.OIDC.Base" />
		<PackageReference Include="ReactiveUI.Fody" />
		<PackageReference Include="ReactiveUI" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BaseApp.ViewModels\BaseApp.ViewModels.csproj" />
	</ItemGroup>

	<ItemGroup>

		<PackageReference Include="AppApi" />
	</ItemGroup>
</Project>
