<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="$([MSBuild]::GetPathOfFileAbove('Solution.Build.props'))" />
	<Import Project="$([MSBuild]::GetPathOfFileAbove('MakePackage.targets'))" />
	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
		<AssemblyName>BaseApp.ViewModels</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="ReactiveUI.Fody" />
		<PackageReference Include="ReactiveUI" />

		<PackageReference Include="LazyMagic.Client.FactoryGenerator" />
		<PackageReference Include="LazyMagic.Client.ModelGenerator" />
		<PackageReference Include="LazyMagic.Client.ViewModels" />
		<PackageReference Include="LazyMagic.Shared" />
		<PackageReference Include="LazyMagic.OIDC.Base" />
		<!--<PackageReference Include="TenantApi" />-->
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="PublicModuleClientInterface" />
		<PackageReference Include="ConsumerModuleClientInterface" />
		<PackageReference Include="StoreModuleClientInterface" />
		<PackageReference Include="ChatModuleClientInterface" />
	</ItemGroup>	
	
</Project>
