<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Razor">
	<Import Project="$(MSBuildProjectDirectory)/../Solution.Build.props" />

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<DebugType>portable</DebugType>		
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	</PropertyGroup>

	<ItemGroup>
		<EmbeddedResource Include="wwwroot\appConfig.js" />
	</ItemGroup>

	<ItemGroup>
		<SupportedPlatform Include="browser" />
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" />
	</ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="ReactiveUI" />
		<PackageReference Include="ReactiveUI.SourceGenerators" PrivateAssets="all" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\BaseApp.BlazorUI\BaseApp.BlazorUI.csproj" />
		<ProjectReference Include="..\ViewModels\ViewModels.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Components\" />
	  <Folder Include="wwwroot\data\" />
	</ItemGroup>

</Project>
